#ifndef __BASE_H
#define __BASE_H


#define PERIPHERAL_BASE             (0x40000000UL)

#define APB1_PERIPHERAL_BASE        PERIPHERAL_BASE
#define APB2_PERIPHERAL_BASE        (PERIPHERAL_BASE + 0x00010000UL)
#define AHB_PERIPHERAL_BASE         (PERIPHERAL_BASE + 0x00020000UL)

#define GPIOA_PERIPHERAL_OFFSET     (0x000800UL)
#define GPIOA_PERIPHERAL             (APB2_PERIPHERAL_BASE + GPIOA_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET     (0x001000UL)
#define GPIOC_PERIPHERAL            (APB2_PERIPHERAL_BASE + GPIOC_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET       (0x001000UL)
#define RCC_PERIPHERAL              (AHB_PERIPHERAL_BASE + RCC_PERIPHERAL_OFFSET)




#endif /* __BASE_H */
																												 
